openapi: 3.0.3
info:
  title: Hello World API
  version: 1.0.0

paths:
  /pizzas:
    get:
      summary: Get all pizzas
      description: Find all pizzas
      operationId: getAllPizzas
      responses:
        '200':
          description: A list of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'
    post:
      summary: Create a pizza
      description: Creates a pizza
      operationId: createPizza
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
      responses:
        '200':
          description: Successful pizza creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
  /pizzas/{name}:
    get:
      summary: Get pizzas by name
      description: Find pizzas by name
      operationId: findPizzaByName
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of pizzas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
components:
  schemas:
    Pizza:
      type: object
      properties:
        name:
          type: string