openapi: 3.0.3
info:
  title: Hello World API
  version: 1.0.0

paths:
  /pizzas:
    get:
      summary: Get pizzas
      description: Get all pizzas or filter by name
      operationId: getPizzas
      parameters:
        - name: name
          in: query
          required: false
          description: Filter pizzas by name
          schema:
            type: string
      responses:
        '200':
          description: A list of pizzas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pizza'

    post:
      summary: Create a pizza
      description: Creates a pizza
      operationId: createPizza
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pizza'
      responses:
        '201':
          description: Successful pizza creation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'

  /pizzas/{id}:
    get:
      summary: Get pizza by ID
      description: Find a pizza by its UUID
      operationId: getPizzaById
      parameters:
        - name: id
          in: path
          required: true
          description: UUID of the pizza
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: A pizza
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pizza'
        '404':
          description: Pizza not found

components:
  schemas:
    Pizza:
      type: object
      required:
        - name
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string