### Get all pizzas (with valid JWT)
### Roles CHEF and CUSTOMER present
GET http://localhost:8080/pizzas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiRGVtbyBVc2VyIiwic3ViIjoiZGVtby11c2VyIiwiZXhwIjoxNzcwNzA4NzcxLCJpYXQiOjE3NzA3MDUxNzEsInJvbGVzIjpbIlJPTEVfQ0hFRiJdfQ.v-OztgK4mXtgu3wH6HYOhbgKZDsgiomC8EAjfDKmLfA

### Role CUSTOMER present
GET http://localhost:8080/pizzas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiRGVtbyBVc2VyIiwic3ViIjoiZGVtby11c2VyIiwiZXhwIjoxNzY5MTc1NTc2LCJpYXQiOjE3NjkxNzE5NzYsInJvbGVzIjpbIlJPTEVfQ1VTVE9NRVIiXX0.KVGU2l2KL_C36o_8HPK_lGIqJfMB2cb9YVD5QULnL0Y

### Get all pizzas (without token - should fail with 401)
GET http://localhost:8080/pizzas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiRGVtbyBVc2VyIiwic3ViIjoiZGVtby11c2VyIiwiZXhwIjoxNzcxNTg3MDk3LCJpYXQiOjE3NzE1ODM0OTcsInJvbGVzIjpbIlJPTEVfQ0hFRiJdfQ.w1JK4ED83_ySuEOtFWgxqWHbHXMxB6rTz7y8aKw74IE

### Create Pizza as Customer
POST http://localhost:8080/pizzas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiRGVtbyBVc2VyIiwic3ViIjoiZGVtby11c2VyIiwiZXhwIjoxNzcwNjIyNTQxLCJpYXQiOjE3NzA2MTg5NDEsInJvbGVzIjpbIlJPTEVfQ1VTVE9NRVIiXX0.R_y0BlqELukrNIdz-mlwLjbSFuOV46KpFpVJ-uOpnLI

### Create Pizza as Chef
POST http://localhost:8080/pizzas
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJuYW1lIjoiRGVtbyBVc2VyIiwic3ViIjoiZGVtby11c2VyIiwiZXhwIjoxNzcwOTk4MjAxLCJpYXQiOjE3NzA5OTQ2MDEsInJvbGVzIjpbIlJPTEVfQ0hFRiJdfQ.QrzTls2qGwL8IJp-lYFDpeTqnBK3BKFd5qUrUyHo0eQ

